#ARQUIVO EM PYTHON COM AS VARIÁVEIS GLOBAIS

BACKGROUND = "#a1a1a1"
FONTE_TEXTO = "Arial"
TAMANHO_TITULO = "20pt"
TAMANHO_TITULO_EIXOS = "15pt"
NUM_MINOR_TICKS = 5
NUM_MAJOR_TICKS_X = 20
NUM_MAJOR_TICKS_Y = 15
LINHAS_GRADE = None

